[package]
name = "moonmodel"
version = "0.1.0"
authors = ["Lyn-liyuan <lyn@intellicloud.ai>"]
edition = "2021"

[dependencies]
moonweb ={ path = "../../"}
clap = { version = "3.0", features = ["derive"] }
serde = {version = "1.0.203", features = ["derive"] }
serde_json = "1.0"